-- ==========================================================
-- Project: Customer Purchase Behavior and Product Insights Analysis
-- Purpose: This SQL script is designed to analyze retail customer 
--          transactions and extract actionable insights regarding 
--          customer behavior, loyalty, product performance, and revenue.
-- ==========================================================

CREATE DATABASE customer_behavior;
USE customer_behavior;
select * from customer limit 20;

-- ==========================================================
-- Query 1: Calculate total revenue generated by each gender
-- Purpose: To understand revenue distribution across male and female customers
-- ==========================================================
select gender, SUM(purchase_amount) as revenue
from customer
group by gender;

-- ==========================================================
-- Query 2: Identify high-spending customers who used a discount
-- Purpose: To find customers who take advantage of promotions but still spend above average
-- ==========================================================
select customer_id, purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer) ;


-- ==========================================================
-- Query 3: Top 5 products with the highest average review rating
-- Purpose: To identify products that are rated most favorably by customers
-- ==========================================================
SELECT 
    item_purchased, 
    ROUND(AVG(CAST(review_rating AS DECIMAL(10,2))), 2) AS `Average Product Rating`
FROM customer
GROUP BY item_purchased
ORDER BY AVG(CAST(review_rating AS DECIMAL(10,2))) DESC
LIMIT 5;


-- ==========================================================
-- Query 4: Compare average purchase amounts for Standard vs. Express shipping
-- Purpose: To assess how shipping method correlates with customer spending
-- ==========================================================
select shipping_type, 
ROUND(AVG(purchase_amount),2)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type;


-- ==========================================================
-- Query 5: Compare spending and revenue between subscribed and non-subscribed customers
-- Purpose: To evaluate the impact of subscription on customer value
-- ==========================================================
SELECT subscription_status,
       COUNT(customer_id) AS total_customers,
       ROUND(AVG(purchase_amount),2) AS avg_spend,
       ROUND(SUM(purchase_amount),2) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue, avg_spend DESC;


-- ==========================================================
-- Query 6: Top 5 products with highest discount application rate
-- Purpose: To identify products most frequently purchased with discounts
-- ==========================================================
SELECT item_purchased,
       ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;


-- ==========================================================
-- Query 7: Segment customers into New, Returning, and Loyal
-- Purpose: To classify customers based on previous purchase behavior
-- ==========================================================
with customer_type as (
SELECT customer_id, previous_purchases,
CASE 
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM customer)

select customer_segment, count(*) AS "Number of Customers" 
from customer_type 
group by customer_segment;


-- ==========================================================
-- Query 8: Top 3 most purchased products within each category
-- Purpose: To analyze product popularity within different categories
-- ==========================================================
WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT item_rank, category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;


-- ==========================================================
-- Query 9: Repeat buyers subscription analysis
-- Purpose: To determine whether repeat buyers (more than 5 purchases) are more likely to subscribe
-- ==========================================================
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;


-- ==========================================================
-- Query 10: Revenue contribution by age group
-- Purpose: To understand which age groups contribute most to total revenue
-- ==========================================================
SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue desc;

